server:
  forward-headers-strategy: framework
  port: 8080

deltavault:
  snapshots-frequency: 5
  s3:
    region: us-east-1
    pathStyle: false
    bucketName: my-test-bucket
  dynamo:
    region: us-east-1