server:
  forward-headers-strategy: framework
  port: 8080

deltavault:
  s3:
    endpoint: http://localhost:4566
    region: us-east-1
    accessKey: test
    secretKey: test
    pathStyle: true
  dynamo:
    endpoint: http://localhost:4566
    region: us-east-1
    accessKey: test
    secretKey: test