/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.14.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.manurasahs.deltavault.port.adapter.clientrest.resources.api;

import io.manurasahs.deltavault.port.adapter.clientrest.resources.model.InputValidationProblem;
import io.manurasahs.deltavault.port.adapter.clientrest.resources.model.VersionsList;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.lang.Nullable;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.14.0")
@Validated
public interface FileHistoryApi {

    /**
     * GET /api/v1/files/{fileName}/history : Get JSON file updates changelog.
     *
     * @param fileName File name. (required)
     * @return JSON at requested version. (status code 200)
     *         or Bad request (4xx) (status code 400)
     *         or Bad request (4xx) (status code 404)
     */
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/v1/files/{fileName}/history",
        produces = { "application/json", "application/problem+json" }
    )
    
    ResponseEntity<VersionsList> apiV1FilesFileNameHistoryGet(
         @PathVariable("fileName") String fileName
    );

}
